### ISSUE TITLE
Parsing eunit macro ?debugVal fails with Error: function_clause

### ISSUE THREAD

**Issue by cypherfox** [inaka/elvis#480] opened 2018-04-13 09:35 UTC
Linting the following module gives me:
```
Error: function_clause when loading file "src/elvis_function_fail.erl".
# src/elvis_function_fail.erl [FAIL]
Error: 'function_clause' while applying rule 'no_debug_call'.
Error: 'function_clause' while applying rule 'dont_repeat_yourself'.
[...all the other rules...]
```
As far as I can tell this only happens with the `?debugVal` macro. I use the `?debug*` eunit macros quite intensively in my tests and they all work fine.

The complete code of the module is:

```
-module(elvis_function_fail).
-include_lib("eunit/include/eunit.hrl").
-export([f/0]).

f() ->
    Val = 10,
?debugVal(Val),
ok.

```

**Comment by elbrujohalcon** [comment] 2018-04-13 10:58
Hi @cypherfox , can you show us your elvis.config and Erlang/OTP version, please?
I tried it in a testing project of mine and it emitted no warnings.

**Comment by cypherfox** [comment] 2018-04-13 11:55
Erlang/OTP: 20

I am using elvis_core (package 0.4.1) via https://github.com/timadorus/rebar3_lint"

elvis.config
```
[{ elvis,
   [ {config,
      [#{ dirs => ["src", "test"]
          , filter => "*.erl"
          , rules => [{elvis_style, line_length,
                       #{ignore => [],
                         limit => 120,
                         skip_comments => false}},
                      {elvis_style, no_tabs},
                      {elvis_style, no_trailing_whitespace},
                      {elvis_style, macro_names, #{ignore => []}},
                      {elvis_style, macro_module_names},
                      {elvis_style, operator_spaces, #{rules => [{right, ","},
                                                                 {right, "++"},
                                                                 {left, "++"}]}},
                      {elvis_style, nesting_level, #{level => 3}},
                      {elvis_style, god_modules,
                       #{limit => 25,
                         ignore => []}},
                      {elvis_style, no_if_expression},
                      {elvis_style, invalid_dynamic_call,
                       #{ignore => [teu_tree, teu_tree_gen]}},
                      {elvis_style, used_ignored_variable,
                        #{ignore => [teu_async_mock_tests]}},
                      {elvis_style, no_behavior_info},
                      {
                       elvis_style,
                       module_naming_convention,
                       #{regex => "^[a-z]([a-z0-9]*_?)*(_SUITE)?$",
                         ignore => []}
                      },
                      {
                       elvis_style,
                       function_naming_convention,
                       #{ regex => "^([a-z][a-z0-9]*_?)([a-z0-9]*_?)*$"}
                      },
                      {elvis_style, state_record_and_type},
                      {elvis_style, no_spec_with_records},
                      {elvis_style, dont_repeat_yourself, #{min_complexity => 20}},
                      {
                       elvis_style,
                       no_debug_call,
                       #{ ignore => [teu_async_mock, teu_ct, teu_perf_measure]}
                      }
                       ]},
       #{ dirs => ["."]
          , filter => "Makefile"
          , rules => [{elvis_project, no_deps_master_erlang_mk, #{ignore => []}},
                      {elvis_project, protocol_for_deps_erlang_mk, #{ignore => []}}]
        },
       #{ dirs => ["."]
          , filter => "rebar.config"
          , rules => [ {elvis_project, no_deps_master_rebar, #{ignore => []}}
                     ]
        },
       #{ dirs => ["."]
          , filter => "elvis.config"
          , ruleset => elvis_config
        }
      ]}
     , {output_format, plain}
   ]
}].
```

**Comment by cypherfox** [comment] 2018-04-13 11:56
Never mind.  I just realised that I am probably actually running elvis_core 0.3.6 due to rebar.lock file.

I will clean this up and be back if need be.

closing the issue for now. Please excuse the hubub

**Comment by elbrujohalcon** [comment] 2018-04-13 12:38
I created the project that I'm attaching [here](https://github.com/inaka/elvis/files/1907337/eff.zip).
Then I run the following commands:
```bash
$ erl -s init stop
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

*** ERROR: Shell process terminated! ***
$ elvis rock
# src/elvis_function_fail.erl [FAIL]
  - line_length
    - Line 8 is too long:     _I_added_this_line = to_get_a_warning, % and it's very very very very very long - a really really long long line - very long.
$ elvis --version
   ______     _
  / __/ /  __(_)__
 / _// / |/ / (_-<
/___/_/|___/_/___/
Version: 0.4.1
Elvis Core Version: 0.3.9
```

Can you do the same?

**Comment by elbrujohalcon** [comment] 2018-04-13 19:34
Ok, that looks like your elvis is not properly compiled. Which is weird since you have the same version of elvis that I have. Let's try this: Please replace your elvis executable with the one attached here and run `elvis rock` again.


[elvis.zip](https://github.com/inaka/elvis/files/1908706/elvis.zip)

**Comment by cypherfox** [comment] 2018-04-13 19:51
```
$ elvis rock
# src/elvis_function_fail.erl [FAIL]
  - line_length
    - Line 8 is too long:     _I_added_this_line = to_get_a_warning, % and it's very very very very very long - a really really long long line - very long.
```

I had my elvis freshly compiled just before running it (`git clone; rebar3 escriptize` as stated in the Readme.md ). As I nomally only use the rebar3 plugin I had never previously build/installed the actual CLI binary.

**Comment by elbrujohalcon** [comment] 2018-04-16 12:10
I'm not sure what's going on there. I run the following commands here and it worked:
```bash
$ git clone git@github.com:inaka/elvis.git
Cloning into 'elvis'...
remote: Counting objects: 2517, done.
remote: Total 2517 (delta 0), reused 0 (delta 0), pack-reused 2517
Receiving objects: 100% (2517/2517), 659.79 KiB | 413.00 KiB/s, done.
Resolving deltas: 100% (1713/1713), done.
$ cd elvis
$ rebar3 escriptize
…lots of output…
$ cd path/to/eff
$ ../path/to/elvis/_build/default/bin/elvis rock
# src/elvis_function_fail.erl [FAIL]
  - line_length
    - Line 8 is too long:     _I_added_this_line = to_get_a_warning, % and it's very very very very very long - a really really long long line - very long.
```

**Comment by elbrujohalcon** [comment] 2018-04-16 12:11
Maybe you can contact the authors of that rebar3 plugin and check if they're doing something different there.

**Comment by jfacorro** [comment] 2018-04-16 13:18
@cypherfox With a repo were we can reproduce the behaviour we could look into what the problem is with that plugin. Would it be possible for you to create it?

**Comment by cypherfox** [comment] 2018-04-17 16:42
@elbrujohalcon: but my local build failed independently of the rebar plugin. I followed the instructions on the elvis Readm to do a fresh install.

I think this may be important: the rebar plugin will pull down elvis_core on each build and compile it fresh. I rust run it on both my local machine (Ubuntu on Windows) as well as my CI/CD Pipeline (the official erlang:latest image), and both created an elvis_core that will throw those errors.

What plattforms are you compiling on?

**Comment by elbrujohalcon** [comment] 2018-04-17 16:51
I'm on a macbook pro, with macOS High Sierra Version 10.13.4 and I install Erlang/OTP through kerl.

**Comment by cypherfox** [comment] 2018-04-17 16:58
@jfacorro This replicates the behaviour with the plugin: 
   https://github.com/cypherfox/elvis_test_build

**Comment by jfacorro** [comment] 2018-04-18 06:15
I've managed to reproduce the problem in `katana-code`'s shell:
```
1> ktn_code:parse_tree([], "-module(bla).\n-include_lib(\"eunit/include/eunit.hrl\").\n-export([f/0]).\nf() -> Val = 10, ?debugVal(Val).").
** exception error: no function clause matching aleppo:legacy_location({var,[{text,"E"},{location,{232,33}}],'E'}) (/Users/juan.facorro/dev/jfacorro/katana-code/_build/default/lib/aleppo/src/aleppo.erl, line 448)
     in function  aleppo:reverse_and_normalize_token_locations_helper/2 (/Users/juan.facorro/dev/jfacorro/katana-code/_build/default/lib/aleppo/src/aleppo.erl, line 472)
     in call from aleppo:process_tree/2 (/Users/juan.facorro/dev/jfacorro/katana-code/_build/default/lib/aleppo/src/aleppo.erl, line 73)
     in call from ktn_code:parse_tree/3 (/Users/juan.facorro/dev/jfacorro/katana-code/_build/default/lib/katana_code/src/ktn_code.erl, line 112)
```

I think the problem is in the way `aleppo` is processing the tokens though, probably the code that does the macro-expansion isn't considering a special case. I will look into it.

**Comment by jfacorro** [comment] 2018-04-19 07:08
UPDATE: I'm still looking into this. I now suspect the `??E` [here](https://github.com/erlang/otp/blob/master/lib/eunit/include/eunit.hrl#L241) is the one that is not being handled properly. The `debugVal` macro does some non-trivial macro things, which `aleppo` is not handling well.

**Comment by jfacorro** [comment] 2018-04-19 21:36
@cypherfox @elbrujohalcon Just opened a PR with a fix in Aleppo, once that's merged it will need to be propagated to `elvis_core` and `elvis`.

**Comment by elbrujohalcon** [comment] 2018-05-05 00:37
Since katana-code is already updated with the change, I'll close this issue and open a new one to update dependencies in elvis_core and another one for updating this repo.

**Closed by elbrujohalcon** 2018-05-05 00:37 UTC
