### ISSUE TITLE
elvis.config file documentation

### ISSUE THREAD

**Issue by ferigis** [inaka/elvis#437] opened 2017-03-01 15:20 UTC
- Create an appropriate documentation for elvis.config file.
- Include an example about how to exclude some given modules from checks (something like [issue#356](https://github.com/inaka/elvis/issues/356) response)

**Comment by zsoci** [comment] 2017-03-01 20:42
Please note when we can use wildcards in the file name rules. Examples would also be easier with wildcarding.

**Comment by elbrujohalcon** [comment] 2018-05-05 00:42
Duplicate of #380

**Closed by elbrujohalcon** 2018-05-05 00:42 UTC
