### ISSUE TITLE
There's no ignore option for the `state_record_and_type` rule

### ISSUE THREAD

**Issue by NAR** [inaka/elvis#551] opened 2020-11-20 09:19 UTC
It is not possible to ignore the warnings from the `state_record_and_type` rule, the code does not check for the `ignore` option. It would be really cool if I could suppress this warning :-)

**Comment by elbrujohalcon** [comment] 2020-11-20 09:38
Have you tried adding the following attribute to your module(s)?

```erlang
-elvis([{elvis_style, state_record_and_type, disable}]).
```

**Comment by NAR** [comment] 2020-11-20 09:56
Now I tried, but still get the error. This is my source file:
```
-module(lint_bug).
-elvis([{elvis_style, state_record_and_type, disable}]).

-behavior(gen_server).

-export([handle_call/3, handle_cast/2, init/1]).

handle_call(_, _, _) ->
  {reply, ok, []}.

handle_cast(_, _) ->
  {noreply, []}.

init(_) ->
  {ok, []}.
```

**Comment by NAR** [comment] 2020-11-20 10:15
I have to add I'm using `elvis` through the `rebar3_lint` plugin, I need to check if using `elvis` directly works or not...

**Comment by elbrujohalcon** [comment] 2020-11-20 10:20
I can confirm this is a bug. Thanks for reporting, @NAR

**Comment by elbrujohalcon** [comment] 2020-11-20 10:23
@paulo-ferraz-oliveira / @Licenser : Can it be that `rebar3_lint` is still using an old version of `elvis_core`? Maybe one without support for `-elvis` or the generic `ignore` property?

**Comment by elbrujohalcon** [comment] 2020-11-20 10:25
Yeah… I think that's it! We need a new release of `elvis_core`. Stay tuned, @NAR … I'll coordinate with @paulo-ferraz-oliveira and @Licenser and let you know.

**Comment by paulo-ferraz-oliveira** [comment] 2020-11-20 12:09
Yes, I would say that `master` `elvis_core` fixes that, but since it's not had a release, so hasn't `rebar3_lint`. I was [in the middle of finishing something](https://github.com/inaka/elvis_core/pull/138) for `elvis_core`, rebased some stuff and got stuck with an unusable version :-) but `master` is OK to release, if @elbrujohalcon's OK with this.

In the meantime could you check if the behavior persists by forcing (via either `rebar.config` or `rebar.lock`) the latest commit on `elvis_core`?

**Comment by paulo-ferraz-oliveira** [comment] 2020-11-20 12:10
> @paulo-ferraz-oliveira / @Licenser : Can it be that `rebar3_lint` is still using an old version of `elvis_core`? Maybe one without support for `-elvis` or the generic `ignore` property?

This is correct. Support for both the directive and the generic ignore is not released (or published to Hex.pm) in either `elvis_core` or `rebar3_lint`.

**Comment by paulo-ferraz-oliveira** [comment] 2020-11-20 12:23
Also related: check https://github.com/inaka/elvis_core/blob/master/test/examples/pass_state_record_and_type_elvis_attr.erl (what @elbrujohalcon was referring to).

**Comment by NAR** [comment] 2020-11-20 14:13
With the latest `elvis_core` the 
```
-elvis([{elvis_style, state_record_and_type, disable}]).
```
line suppresses the warning, I can confirm that. I could only test with `elvis` and not with the `rebar3_lint` plugin, but `elvis` worked with the `master` version of `elvis_core` (didn't suppress the warning with `0.6.0` though).

**Comment by elbrujohalcon** [comment] 2020-11-20 14:23
Alright… I'll see if I can cut a release of `elvis_core` next Monday.

**Comment by elbrujohalcon** [comment] 2020-11-23 08:57
Aaaaand… project-fifo/rebar3_lint#19

**Comment by paulo-ferraz-oliveira** [comment] 2020-11-23 18:53
@NAR, I'm closing this since it's only a matter of releasing `rebar3_lint` for your issue to be fixed. Let us know if further issues come up.

**Closed by paulo-ferraz-oliveira** 2020-11-23 18:53 UTC
Labels: bug
