### ISSUE TITLE
Trouble using built escript with recent builds.

### ISSUE THREAD

**Issue by emauton** [inaka/elvis#333] opened 2016-01-20 12:56 UTC
Hello, team Elvis. Thanks for the tool! I'm having trouble using building recent tags.

•worky@12:26•/home/cian/elvis➤ git status
HEAD detached at 0.2.6

•worky@12:26•/home/cian/elvis➤ make escript
... all OK ...

•worky@12:27•/home/cian/elvis➤ which erl
/home/cian/I/OTP-17.5.6.1/bin/erl

•worky@12:27•/home/cian/elvis➤ erl
Erlang/OTP 17 [erts-6.4.1.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.4.1.1  (abort with ^G)
1> q().
ok

•worky@12:28•/home/cian/elvis➤ ./elvis -c config/elvis.config rock
Loading files...
Loading src/elvis.erl
Error: undef when loading file "src/elvis.erl".
... lots of this ...

To me, it looks like the escript can't find elvis_core's elvis_file:load_file_data/2.

Does this look familiar? Any ideas on what might be wrong with my environment?

Same for 0.2.5, 0.2.4. I can successfully build and run at tag 0.2.3, but then a lot of functionality in my project's config file seems to be unsupported.

This is happening both on my local machine and on a (built from scratch) CI image using the same Erlang version. The CI builds were working cleanly as of about a month ago IIRC.

Full output from an Elvis run (built as above):

```
•worky@12:55•/home/cian/elvis➤ ./elvis -v
   ______     _   
  / __/ /  __(_)__
 / _// / |/ / (_-<
/___/_/|___/_/___/
Version: 0.2.6
•worky@12:55•/home/cian/elvis➤ ./elvis -c config/elvis.config rock
Loading files...
Loading src/elvis.erl
Error: undef when loading file "src/elvis.erl".
Loading src/elvis_git.erl
Error: undef when loading file "src/elvis_git.erl".
Loading src/elvis_webhook.erl
Error: undef when loading file "src/elvis_webhook.erl".
Applying rules...
# src/elvis.erl [FAIL]
Error: 'undef' while applying rule 'no_debug_call'.
Error: 'undef' while applying rule 'dont_repeat_yourself'.
Error: 'undef' while applying rule 'no_spec_with_records'.
Error: 'undef' while applying rule 'state_record_and_type'.
Error: 'undef' while applying rule 'function_naming_convention'.
Error: 'undef' while applying rule 'module_naming_convention'.
Error: 'undef' while applying rule 'no_behavior_info'.
Error: 'undef' while applying rule 'used_ignored_variable'.
Error: 'undef' while applying rule 'invalid_dynamic_call'.
Error: 'undef' while applying rule 'no_if_expression'.
Error: 'undef' while applying rule 'god_modules'.
Error: 'undef' while applying rule 'nesting_level'.
Error: 'undef' while applying rule 'operator_spaces'.
Error: 'undef' while applying rule 'macro_module_names'.
# src/elvis_git.erl [FAIL]
Error: 'undef' while applying rule 'no_debug_call'.
Error: 'undef' while applying rule 'dont_repeat_yourself'.
Error: 'undef' while applying rule 'no_spec_with_records'.
Error: 'undef' while applying rule 'state_record_and_type'.
Error: 'undef' while applying rule 'function_naming_convention'.
Error: 'undef' while applying rule 'module_naming_convention'.
Error: 'undef' while applying rule 'no_behavior_info'.
Error: 'undef' while applying rule 'used_ignored_variable'.
Error: 'undef' while applying rule 'invalid_dynamic_call'.
Error: 'undef' while applying rule 'no_if_expression'.
Error: 'undef' while applying rule 'god_modules'.
Error: 'undef' while applying rule 'nesting_level'.
Error: 'undef' while applying rule 'operator_spaces'.
Error: 'undef' while applying rule 'macro_module_names'.
# src/elvis_webhook.erl [FAIL]
Error: 'undef' while applying rule 'no_debug_call'.
Error: 'undef' while applying rule 'dont_repeat_yourself'.
Error: 'undef' while applying rule 'no_spec_with_records'.
Error: 'undef' while applying rule 'state_record_and_type'.
Error: 'undef' while applying rule 'function_naming_convention'.
Error: 'undef' while applying rule 'module_naming_convention'.
Error: 'undef' while applying rule 'no_behavior_info'.
Error: 'undef' while applying rule 'used_ignored_variable'.
Error: 'undef' while applying rule 'invalid_dynamic_call'.
Error: 'undef' while applying rule 'no_if_expression'.
Error: 'undef' while applying rule 'god_modules'.
Error: 'undef' while applying rule 'nesting_level'.
Error: 'undef' while applying rule 'operator_spaces'.
Error: 'undef' while applying rule 'macro_module_names'.
Loading files...
Loading ./Makefile
Applying rules...
# ./Makefile [OK]
Loading files...
Loading ./rebar.config
Applying rules...
# ./rebar.config [OK]
Loading files...
Loading ./elvis.config
Applying rules...
# ./elvis.config [OK]
```

**Comment by jfacorro** [comment] 2016-01-20 14:54
@emauton I found this problem recently as well. In my case the issue is that the `aleppo` library doesn't get compiled because I get a bunch of warnings like the following:

```
src/aleppo_parser.erl:3080: attribute 'dialyzer' after function definitions
```

If I check for `*.beam` files in the `./deps/inaka_aleppo/ebin` folder I find none:

```
➜  elvis ll deps/inaka_aleppo/ebin/
total 8
-rw-r--r--  1 jfacorro  staff   376B Jan 20 11:50 aleppo.app
```

I think this change might be related to the latest changes we brought from upstream into inaka's fork of the `aleppo` library.

**Comment by jfacorro** [comment] 2016-01-20 16:12
@emauton I just found a strange behavior when `erlang.mk` builds the `inaka_aleppo` dep. Could you please check what does the line that includes the `yeccpre.hrl` looks like in the file `deps/inaka_aleppo/src/aleppo_parser.erl`? This should be generated when running `make`.

I ran the following:

```
➜  elvis make distclean all
# ... a bunch of output
mkdir -p ebin
erl -make
Recompile: src/aleppo_parser
src/aleppo_parser.erl:180: attribute 'dialyzer' after function definitions
# A bunch of lines with the same error
cp src/aleppo.app.src ebin/aleppo.app
# ... a bunch of output
➜  elvis grep -rn "file.*yeccpre.hrl" deps/inaka_aleppo/src
deps/inaka_aleppo/src/aleppo_parser.erl:4:-file("/usr/local/lib/erlang/lib/parsetools-2.1/include/yeccpre.hrl", 0).
```

This shows that `erlc` seems to be using the `parsetools` from a location other than the current Erlang version I'm actually running:

```
➜  elvis which erl
/Users/jfacorro/dev/erlang/17.5/bin/erl
```

The weirdest is that if I delete the file and then run `make` again, there are no errors and the `aleppo_parser.erl` generated by the compiler is different from the previous:

```
➜  elvis rm deps/inaka_aleppo/src/aleppo_parser.erl
➜  elvis make
erlc -o src/ src/aleppo_parser.yrl
src/aleppo_parser.yrl: Warning: conflicts: 1 shift/reduce, 0 reduce/reduce
mkdir -p ebin
erl -make
Recompile: src/aleppo_parser
Recompile: src/aleppo
cp src/aleppo.app.src ebin/aleppo.app
make -f c_src/Makefile.erlang.mk
make[2]: Nothing to be done for `all'.
➜  elvis grep -rn "file.*yeccpre.hrl" deps/inaka_aleppo/src
deps/inaka_aleppo/src/aleppo_parser.erl:4:-file("/Users/jfacorro/dev/erlang/17.5/lib/parsetools-2.0.12/include/yeccpre.hrl", 0).
```

**Comment by emauton** [comment] 2016-01-21 11:38
Yep, confirmed the same thing here:
```
•worky@11:32•/home/cian/elvis➤ which erl
/home/cian/I/OTP-17.5.6.1/bin/erl
•worky@11:32•/home/cian/elvis➤ grep -rn "file.*yeccpre.hrl" deps/inaka_aleppo/src
deps/inaka_aleppo/src/aleppo_parser.erl:4:-file("/usr/local/lib/erlang/lib/parsetools-2.1/include/yeccpre.hrl", 0).
```

Trying the same deletion:
```
•worky@11:33•/home/cian/elvis➤ rm deps/inaka_aleppo/src/aleppo_parser.erl
•worky@11:34•/home/cian/elvis➤ make
[... output ...]
•worky@11:34•/home/cian/elvis➤ grep -rn "file.*yeccpre.hrl" deps/inaka_aleppo/src
deps/inaka_aleppo/src/aleppo_parser.erl:4:-file("/home/cian/I/OTP-17.5.6.1/lib/parsetools-2.0.12/include/yeccpre.hrl", 0).
```

After this, "make escript" produces a working script:
```
•worky@11:36•/home/cian/elvis➤ make escript
[... output ...]
•worky@11:36•/home/cian/elvis➤ ./elvis -c config/elvis.config rock
Loading files...
Loading src/elvis.erl
Loading src/elvis_git.erl
Loading src/elvis_webhook.erl
Applying rules...
# src/elvis.erl [OK]
# src/elvis_git.erl [OK]
# src/elvis_webhook.erl [OK]
Loading files...
Loading ./Makefile
Applying rules...
# ./Makefile [OK]
Loading files...
Loading ./rebar.config
Applying rules...
# ./rebar.config [OK]
Loading files...
Loading ./elvis.config
Applying rules...
# ./elvis.config [OK]
```

So I guess something about inaka_aleppo's initial build environment is discarding the top-level PATH etc. setup?

**Comment by jfacorro** [comment] 2016-01-21 13:44
@emauton I found the problem yesterday. The `inaka_aleppo` package is including the `aleppo_parser.erl` file which should actually be generated in the compilation process. We are working on fixing this issue. Thank you for reporting it!

**Comment by emauton** [comment] 2016-01-21 13:49
Superb, thank you very much!

**Comment by jfacorro** [comment] 2016-01-21 19:09
@emauton It should work now. Could you please verify? Thanks!

**Comment by emauton** [comment] 2016-01-22 11:19
Aside: I don't understand your dependency management story here: how can I rebuild at the same release tag and have different effects? Please consider specifying dependencies such that builds are repeatable: a working tag stays working, a broken one stays broken. It's bad UX for me to be able to build two different 0.2.6 with magical things happening underneath.

In any case, this now works when the escript is run directly from elvis' homedir against itself, but when I copy it to my ~/bin directory I continue to see issues, weirdly on some files but not others:

```
•worky@11:12•/home/cian/project➤ elvis rock
Loading files...
Loading apps/project/src/project.erl
Loading apps/project/src/project_app.erl
Loading apps/project/src/project_console.erl
Loading apps/project/src/project_inspect.erl
Loading apps/project/src/project_service.erl
Error: function_clause when loading file "apps/project/src/project_service.erl".
Loading apps/project/src/project_buffer.erl
Error: function_clause when loading file "apps/project/src/project_buffer.erl".
[... lots more of this ...]
Applying rules...
# apps/project/src/project.erl [OK]
# apps/project/src/project_app.erl [OK]
# apps/project/src/project_console.erl [OK]
# apps/project/src/project_inspect.erl [OK]
# apps/project/src/project_service.erl [FAIL]
Error: 'function_clause' while applying rule 'no_debug_call'.
Error: 'function_clause' while applying rule 'dont_repeat_yourself'.
Error: 'function_clause' while applying rule 'no_spec_with_records'.
Error: 'function_clause' while applying rule 'state_record_and_type'.
Error: 'function_clause' while applying rule 'function_naming_convention'.
Error: 'function_clause' while applying rule 'module_naming_convention'.
Error: 'function_clause' while applying rule 'no_behavior_info'.
Error: 'function_clause' while applying rule 'used_ignored_variable'.
Error: 'function_clause' while applying rule 'invalid_dynamic_call'.
Error: 'function_clause' while applying rule 'no_if_expression'.
Error: 'function_clause' while applying rule 'god_modules'.
Error: 'function_clause' while applying rule 'nesting_level'.
Error: 'function_clause' while applying rule 'operator_spaces'.
Error: 'function_clause' while applying rule 'macro_module_names'.
[... lots more of this ...]
```

Let me know if you'd like me to check anything else.

**Comment by jfacorro** [comment] 2016-01-22 13:43
@emauton Since the 0.2.6 release was a recent one, I moved the tag for that release to a commit where the build was working. In general I agree with what you say. Since this new problem you mention seems to be a bug in the actual `aleppo` code, we will fix aleppo and create a new `0.2.7` release.

**Comment by emauton** [comment] 2016-01-22 13:50
Cool, thank you. And carping about dependencies aside, thanks again for Elvis, I love having it run as part of my CI. :o)

**Comment by jfacorro** [comment] 2016-01-22 20:07
@emauton We love having people use `elvis` :smile:. There is a new `0.2.7` release, please try it out and let us know.  I'm closing this issue for now, feel free to re-open it if you find any problems.

**Closed by jfacorro** 2016-01-22 20:07 UTC
