### ISSUE TITLE
Uncorrect detecting rule missing space after "++"

### ISSUE THREAD

**Issue by Euen** [inaka/elvis#320] opened 2015-12-31 13:44 UTC
The rule don't work with ++ between ""

i.e.
```
Name = "First"++"Last",
```

**Comment by jaseemabid** [comment] 2016-01-13 06:58
Duplicate of #319

**Comment by harenson** [comment] 2016-01-13 19:06
Fixed in https://github.com/inaka/elvis_core/pull/20

**Closed by harenson** 2016-01-13 19:06 UTC
Labels: bug, elvis_core
